---
type: wan_router
wan_mode: cv-pathfinder
wan_router:
  nodes:
    - bgp_as: 65000
      name: l3-port-channel-sub-interface-with-member-interfaces
      id: 1
      loopback_ipv4_pool: 192.168.0.0/24
      vtep_loopback_ipv4_pool: 192.168.1.0/24
      l3_interfaces:
        - name: Ethernet5
          wan_carrier: FOO
          ip_address: 172.16.0.3/30
      l3_port_channels:
        - name: Port-Channel5
          peer: peer2
          peer_port_channel: Port-Channel15
          peer_ip: 192.168.1.15
          member_interfaces:
            - name: Ethernet1/19
              peer_interface: Ethernet1/19
            - name: Ethernet1/20
              peer_interface: Ethernet1/20
        - name: Port-Channel5.108
          encapsulation_dot1q_vlan: 108
          member_interfaces:
            - name: Ethernet1/19
              peer_interface: Ethernet1/19
          peer: peer2
          peer_port_channel: Port-Channel15.100
          peer_ip: 192.168.1.15
          ip_address: 172.16.0.2/30

wan_carriers:
  - name: FOO
    path_group: INTERNET
    trusted: true

wan_path_groups:
  - id: 100
    name: INTERNET

expected_error_message: >-
  L3 Port-Channel sub-interface 'Port-Channel5.108' has 'member_interfaces' set. This is not a valid setting.
